export default {
  biryani: require('../assets/biryani.jpeg'),
  coffe: require('../assets/coffe.jpeg'),
  ojuice: require('../assets/ojuice.jpeg'),
  pizza1: require('../assets/pizza1.jpeg'),
  summerlemon: require('../assets/summerlemon.jpeg'),
  dosa: require('../assets/dosa.jpeg'),
  greenbean: require('../assets/greenbean.jpeg'),
  koreanfood: require('../assets/koreanfood.jpeg'),
  roll: require('../assets/roll.jpeg'),
  sushi: require('../assets/sushi.jpeg'),
  seaFood: require('../assets/seaFood.jpeg'),
  ramen: require('../assets/ramen.jpeg'),
  pasta: require('../assets/pasta.jpeg'),
  veg: require('../assets/veg.png'),
  nonveg: require('../assets/non-veg.png'),
  fssai: require('../assets/Fssai.svg'),
  fssai2: require('../assets/fssai2.png'),
  cake: require('../assets/cake.jpeg'),
};
