export const types = {
  CHANGE_IN_COUNT: 'CHANGE_IN_COUNT',
  CHANGE_IN_COUNT_SUCCESS: 'CHANGE_IN_COUNT_SUCCESS',
  CHANGE_IN_COUNT_FAILURE: 'CHANGE_IN_COUNT_FAILURE',

  COUNT_TOTALPRICE: 'COUNT_TOTALPRICE',
  COUNT_TOTALPRICE_SUCCESS: 'COUNT_TOTALPRICE_SUCCESS',
  COUNT_TOTALPRICE_FAILURE: 'COUNT_TOTALPRICE_FAILURE',
};
